annotations:
  artifacthub.io/alternativeName: fluent-bit
  artifacthub.io/changes: |-
    - kind: changed
      description: "Update _Fluent Bit_ OCI image to [v4.0.3](https://github.com/fluent/fluent-bit/releases/tag/v4.0.3). ([#1197](https://github.com/stevehipwell/helm-charts/pull/1197)) _@stevehipwell_"
apiVersion: v2
appVersion: 4.0.3
description: Helm chart for Fluent Bit running as a collector DaemonSet.
home: https://fluentbit.io/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/fluent-bit-collector/icon.png
keywords:
- fluent
- fluentd
- fluent bit
- logging
- collector
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
  url: https://github.com/stevehipwell
name: fluent-bit-collector
sources:
- https://github.com/fluent/fluent-bit/
- https://github.com/stevehipwell/helm-charts/
type: application
version: 0.17.3
