apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
  - name: nginx
    releaseName: nginx
    namespace: default
    valuesFile: ../../../../helm/nginx/values.yaml
