apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
nodes:
  - role: control-plane
    image: kindest/node:v1.32.1
  - role: worker
    image: kindest/node:v1.32.1
  - role: worker
    image: kindest/node:v1.32.1
