apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  source:
    repoURL: 'https://github.com/jjchange10/argocd_practice'
    targetRevision: main
    path: applications/cert-manager/overlays/stg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
