apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-kustomize
  namespace: argocd
spec:
  project: external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  source:
    repoURL: 'https://github.com/jjchange10/argocd_practice'
    targetRevision: main
    path: applications/eso-kustomize/overlays/stg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
