apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  sources:
    - repoURL: 'https://charts.external-secrets.io'
      targetRevision: v0.16.1
      chart: external-secrets
      helm:
        valueFiles:
          - $values/helm/eso/values.yaml
    - repoURL: https://github.com/jjchange10/argocd_practice
      targetRevision: main
      ref: values
    
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
