apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit-kustomize
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fluent-bit-collector
  source:
    repoURL: 'https://github.com/jjchange10/argocd_practice'
    targetRevision: main
    path: applications/fluentbit/overlays/stg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
