apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-kustomize
  namespace: argocd
spec:
  project: nginx
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/jjchange10/argocd_practice'
    targetRevision: main
    path: applications/nginx/overlays/stg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
