---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../bases

helmCharts:
- name: eck-operator-crds
  repo: https://helm.elastic.co
  releaseName: elastic-operator-crds
  namespace: elastic-system
  version: 2.10.0
- name: eck-operator
  repo: https://helm.elastic.co
  releaseName: elastic-operator
  namespace: elastic-system
  version: 2.10.0
  valuesFile: ../../../helm/eck-operator/values.yaml
