name: ESO Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 3.13.0
    
    - name: Print Helloworld
      run: echo $GITHUB_EVENT_PATH
    
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
  
    
    - name: Delete Comments on Pull Request
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=1
        comments=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -X GET \
                 "https://api.github.com/repos/${{ github.repository }}/issues/1/comments")
        
        for comment in $(echo $comments | jq -r '.[] | .url'); do
          echo $comment
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -X DELETE \
                 $comment
        done

    - name: Comment on Pull Request
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=1
        COMMENT_BODY="Build result: Helloworld"
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
             -X POST \
             -d "{\"body\": \"${COMMENT_BODY}\"}" \
             "https://api.github.com/repos/${{ github.repository }}/issues/1/comments"