name: ESO Application CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'applications/eso.yaml'
      - 'helm/argocd/eso/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'applications/eso.yaml'
      - 'helm/argocd/eso/**'
  workflow_dispatch:

jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 3.13.0
    
    - name: Install Kustomize
      uses: asdf-vm/actions/install@v3
      with:
        tool_version: |
          kustomize 5.1.0
    
    - name: Print Helloworld
      run: echo "Helloworld"
    
    - name: Comment on Pull Request
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        COMMENT_BODY="Build result: Helloworld"
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
             -X POST \
             -d "{\"body\": \"${COMMENT_BODY}\"}" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
