name: "[ARC] argocd CI"
on:
  workflow_dispatch:

jobs:
  argocd-ci:
    name: "[ARC] argocd CI"
    runs-on: arc-runner-set
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

   # https://github.com/google-github-actions/setup-gcloud
    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin,kubectl"

    - name: "test"
      run: |
        touch testfile && rm testfile

    - name: "Install Argo CD CLI"
      run: |
        curl -sSL -o argocd \
          https://github.com/argoproj/argo-cd/releases/download/v3.0.6/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/

    - name: CI Kubernetes ArgoCD
      run: |
        ./ci-kubernetes-argocd.sh helm stg
