name: "[ARC] argocd CI"
on:
  workflow_dispatch:

jobs:
  argocd-ci:
    name: "[ARC] argocd CI"
    runs-on: arc-runner-set
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

   # https://github.com/google-github-actions/setup-gcloud
    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "kubectl"

    - name: "test"
      run: |
        touch testfile && rm testfile

    - name: "Set up ArgoCD CLI"
      run: |
        curl -fL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v3.0.6/argocd-linux-amd64
        mv argocd-linux-amd64 argocd
        chmod +x argocd
        sudo mv argocd /usr/local/bin/
        env
        argocd version --client

    - name: CI Kubernetes ArgoCD
      run: |
        ./ci-kubernetes-argocd.sh helm stg
